Update master_travelfusionapi.yml

diff --git a/.github/workflows/master_travelfusionapi.yml b/.github/workflows/master_travelfusionapi.yml
--- a/.github/workflows/master_travelfusionapi.yml
+++ b/.github/workflows/master_travelfusionapi.yml
@@ -26,13 +26,13 @@ jobs:
 
       - name: 🔎 Check if csproj exists
         run: |
-          test -f ./TravelFusionLean/TravelFusionLean/TravelFusionLeanApi/TravelFusionLeanApi.csproj && echo "✅ Project found!" || echo "❌ Project NOT found!"
+          test -f ./TravelFusionLean/TravelFusionLeanApi/TravelFusionLeanApi.csproj && echo "✅ Project found!" || echo "❌ Project NOT found!"
 
       - name: Restore, build and publish API
         run: |
-          dotnet restore ./TravelFusionLean/TravelFusionLean/TravelFusionLeanApi/TravelFusionLeanApi.csproj
-          dotnet build ./TravelFusionLean/TravelFusionLean/TravelFusionLeanApi/TravelFusionLeanApi.csproj --configuration Release
-          dotnet publish ./TravelFusionLean/TravelFusionLean/TravelFusionLeanApi/TravelFusionLeanApi.csproj --configuration Release --output ./publish
+          dotnet restore ./TravelFusionLean/TravelFusionLeanApi/TravelFusionLeanApi.csproj
+          dotnet build ./TravelFusionLean/TravelFusionLeanApi/TravelFusionLeanApi.csproj --configuration Release
+          dotnet publish ./TravelFusionLean/TravelFusionLeanApi/TravelFusionLeanApi.csproj --configuration Release --output ./publish
 
       - name: Upload API artifact
         uses: actions/upload-artifact@v4
